# Generated by Django 5.2.5 on 2025-08-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
