# Generated by Django 5.2.5 on 2025-08-13 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرّف الجهاز')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('allowed', models.BooleanField(default=True, verbose_name='مسموح')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='أول ظهور')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جهاز مستخدم',
                'verbose_name_plural': 'أجهزة المستخدمين',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
