# Generated by Django 5.2.5 on 2025-09-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='PayPal Client ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='paypal_secret_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='PayPal Secret (encrypted)'),
        ),
    ]
