# Generated by Django 5.2.5 on 2025-10-20 04:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_paypal_client_id_user_paypal_secret_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerBilling',
            fields=[
            ],
            options={
                'verbose_name': 'بيانات باي بال (للمدرب)',
                'verbose_name_plural': 'بيانات باي بال (للمدرّبين)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
