# Generated by Django 5.2.5 on 2025-08-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='الاسم (اختياري)')),
                ('consent', models.BooleanField(default=True, verbose_name='موافقة على التواصل')),
                ('source', models.CharField(blank=True, max_length=150, null=True, verbose_name='المصدر (مثلاً: صفحة درس)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور')),
            ],
            options={
                'verbose_name': 'زائر',
                'verbose_name_plural': 'الزوّار',
                'ordering': ['-created_at'],
            },
        ),
    ]
