# Generated by Django 5.2.5 on 2025-08-13 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('learning', '0003_question_answeroption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('frozen', 'مجمّد'), ('suspended', 'معلّق'), ('cancelled', 'ملغى')], default='active', max_length=12, verbose_name='الحالة')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بدء الاشتراك')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء (اختياري)')),
                ('freeze_days_used', models.PositiveIntegerField(default=0, verbose_name='أيام التجميد المستهلكة (حد 90)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course', verbose_name='الدورة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
