# Generated by Django 5.2.5 on 2025-08-13 08:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_enrollment'),
        ('learning', '0003_question_answeroption'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(verbose_name='رقم القسط')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('due', 'مستحق'), ('paid', 'مدفوع'), ('overdue', 'متأخر')], default='due', max_length=12, verbose_name='الحالة')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ السداد')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='خصم مطبّق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='commerce.enrollment', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'قسط اشتراك',
                'verbose_name_plural': 'أقساط الاشتراك',
                'ordering': ['step'],
                'unique_together': {('enrollment', 'step')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentPartAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_step', models.PositiveSmallIntegerField(verbose_name='يتاح عند القسط رقم')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='تم الفتح في')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_access', to='commerce.enrollment', verbose_name='الاشتراك')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_access', to='learning.coursepart', verbose_name='الجزء')),
            ],
            options={
                'verbose_name': 'سماحية جزء ضمن اشتراك',
                'verbose_name_plural': 'سماحيات الأجزاء ضمن اشتراك',
                'ordering': ['unlock_step'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'unlock_step'), name='uniq_enrollment_unlock_step')],
                'unique_together': {('enrollment', 'part')},
            },
        ),
    ]
