# Generated by Django 5.2.5 on 2025-09-06 23:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_enrollmentinstallment_enrollmentpartaccess'),
        ('learning', '0005_course_allow_installments_course_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('percent', models.DecimalField(decimal_places=2, help_text='مثلاً 15 يعني 15% خصم', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم (%)')),
                ('active_from', models.DateTimeField(blank=True, null=True, verbose_name='يبدأ من')),
                ('active_to', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('enabled', models.BooleanField(default=True, verbose_name='مُفعّل')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='اتركه فارغًا لو غير محدود', null=True, verbose_name='حد الاستخدام')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستخدام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('full', 'دفع كامل'), ('installment', 'قسط')], max_length=12, verbose_name='طريقة الدفع')),
                ('step', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='رقم القسط')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='العملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ النهائي')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('paypal_order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('paypal_capture_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('created', 'تم الإنشاء'), ('approved', 'موافق عليه'), ('captured', 'تم التحصيل'), ('failed', 'فشل')], default='created', max_length=12, verbose_name='الحالة')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='استجابة باي بال (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.coupon', verbose_name='كوبون')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='learning.course', verbose_name='الدورة')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='commerce.enrollment', verbose_name='الاشتراك')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='commerce.enrollmentinstallment', verbose_name='القسط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
