# Generated by Django 5.2.5 on 2025-09-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_coupon_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank', 'تحويل بنكي')], default='paypal', max_length=12),
        ),
    ]
