# Generated by Django 5.2.5 on 2025-09-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='frozen_started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='frozen_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
