# Generated by Django 5.2.5 on 2025-09-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_enrollment_frozen_started_at_enrollment_frozen_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='expires_at',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
    ]
