# Generated by Django 5.2.5 on 2025-09-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_alter_enrollment_expires_at'),
    ]

    operations = [
    ]
