# Generated by Django 5.2.5 on 2025-09-11 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_fill_expires_at'),
        ('learning', '0007_course_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='learning.course', verbose_name='الدورات المسموح بها'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='المالك (اختياري)'),
        ),
    ]
