# Generated by Django 5.2.5 on 2025-10-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_coupon_courses_coupon_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
    ]
