# Generated by Django 5.2.5 on 2025-09-09 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0007_enrollment_frozen_started_at_enrollment_frozen_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='العنوان (Subject)')),
                ('body_html', models.TextField(verbose_name='HTML المحتوى')),
                ('body_text', models.TextField(blank=True, null=True, verbose_name='النص العادي (اختياري)')),
                ('filter_json', models.JSONField(default=dict, verbose_name='فلاتر الاستهداف')),
                ('total_targets', models.PositiveIntegerField(default=0, verbose_name='عدد المستهدفين')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='تم إرساله')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sending', 'جارٍ الإرسال'), ('done', 'مكتمل')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='sent', max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.visitoremailcampaign')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.visitor')),
            ],
        ),
    ]
