# Generated by Django 5.2.5 on 2025-08-13 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدورة')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='المعرف اللطيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف مختصر')),
                ('has_certificate', models.BooleanField(default=True, verbose_name='شهادة إتمام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoursePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'أ'), ('B', 'ب'), ('C', 'ج')], max_length=1, verbose_name='الرمز')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الجزء')),
                ('description', models.TextField(blank=True, verbose_name='وصف الجزء')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='مُفعّل')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='learning.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'جزء',
                'verbose_name_plural': 'الأجزاء',
                'ordering': ['order_index'],
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الفصل')),
                ('summary_pdf_url', models.TextField(blank=True, verbose_name='ملف الملخص PDF (رابط)')),
                ('quiz_total_questions', models.PositiveIntegerField(default=0, verbose_name='إجمالي أسئلة البنك')),
                ('quiz_random_take', models.PositiveIntegerField(default=20, verbose_name='عدد الأسئلة العشوائية في كل محاولة')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='learning.coursepart', verbose_name='الجزء')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الموضوع')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.chapter', verbose_name='الفصل')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'المواضيع',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدرس')),
                ('video_url', models.TextField(verbose_name='رابط الفيديو')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='متاح للمعاينة مجانًا')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة بالثواني')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.topic', verbose_name='الموضوع')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['order_index'],
            },
        ),
    ]
