# Generated by Django 5.2.5 on 2025-08-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lessonview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('type', models.CharField(choices=[('text', 'نصي'), ('table', 'جدول')], default='text', max_length=12, verbose_name='النوع')),
                ('table_json', models.JSONField(blank=True, null=True, verbose_name='جدول السؤال (JSON)')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح عند الخطأ')),
                ('is_active', models.BooleanField(default=True, verbose_name='مُفعّل')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.chapter', verbose_name='الفصل')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'أسئلة الفصل',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص الاختيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة؟')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'اختيار',
                'verbose_name_plural': 'اختيارات السؤال',
                'ordering': ['id'],
            },
        ),
    ]
