# Generated by Django 5.2.5 on 2025-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_question_answeroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='صورة الدورة'),
        ),
    ]
