# Generated by Django 5.2.5 on 2025-08-30 19:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_installments',
            field=models.BooleanField(default=False, verbose_name='تسمح بالدفع على أقساط؟'),
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='USD', max_length=8, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='course',
            name='installments_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = دفع كامل مرة واحدة', verbose_name='عدد الأقساط (إن وُجد)'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='سعر الدورة'),
        ),
    ]
