# Generated by Django 5.2.5 on 2025-09-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_course_allow_installments_course_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم واتساب (اختياري)')),
                ('subject', models.CharField(max_length=200, verbose_name='العنوان / موضوع الرسالة')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_handled', models.BooleanField(default=False, verbose_name='تمت المعالجة؟')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل تواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
