# Generated by Django 5.2.5 on 2025-10-08 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_course_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('vimeo', 'Vimeo')], default='vimeo', max_length=30, verbose_name='مزود الفيديو')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفيديو')),
                ('video_id', models.CharField(db_index=True, max_length=200, verbose_name='Video ID / URL')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة بالثواني')),
                ('encode_progress', models.PositiveIntegerField(blank=True, null=True, verbose_name='نسبة المعالجة %')),
                ('transcoding_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حالة الترانسكود')),
                ('thumbnail_url', models.URLField(blank=True, null=True, verbose_name='صورة مصغّرة')),
                ('meta', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشت في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّلت في')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_assets', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'فيديو مرفوع',
                'verbose_name_plural': 'فيديوهات مرفوعة',
                'ordering': ['-created_at'],
            },
        ),
    ]
