# Generated by Django 5.2.5 on 2025-10-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_videoasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='التصنيف (اختياري)')),
                ('question', models.CharField(max_length=255, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='مُفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['category', 'order_index', 'id'],
            },
        ),
    ]
