# Generated by Django 5.2.5 on 2025-10-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='أُنشئ في'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='عُدّل في'),
        ),
    ]
